### ISSUE TITLE
Please upgrade rmccue/requests with security vulnerability.

### ISSUE THREAD

**Issue by JoyceBabu** [razorpay/razorpay-php#220]
`rmccue/requests v1.7.0`  has a security vulnerability.  Due to this, [Roave/SecurityAdvisories](https://packagist.org/packages/roave/security-advisories) is preventing the installation of `razorpay/razorpay` package.

`rmccue/requestsv1.8.0` is available with a fix for the vulnerability.

Can you please  release a new version with the updated dependency?

**Comment by robbieaverill** [comment]
Bump @ramth05 @rkamath3 @harman28 @amitmerchant1990  - pinging you because you're the latest in the list of commits. This is a critical security vulnerability and must be updated as soon as possible. Please change your dependency constraint to something like `^1.8.0` instead of specifying concrete versions.

**Comment by robbieaverill** [comment]
https://github.com/razorpay/razorpay-php/blob/2.6.1/composer.json#L27 includes the updated dependency. Thanks to the maintainers for getting this done quickly.

**Comment by JoyceBabu** [comment]
Thanks.
