### ISSUE TITLE
Patyment Id is not creating via API

### ISSUE THREAD

**Issue by Arfat-Mughal** [razorpay/razorpay-php#268]
Customer id created
Order_id created
Did not getting payment_id ;(

**Use like this with orginal order_id and other values but still got Error** 
`$api->payment->createPaymentJson(array('amount' => 100,'currency' => 'INR','email' => 'gaurav.kumar@example.com','contact' => '9123456789','order_id' => 'order_I6LVPRQ6upW3uh','method' => 'card','card' => array('number' => '4854980604708430','cvv' => '123','expiry_month' => '12','expiry_year' => '21','name' => 'Gaurav Kumar')));`

Error => 
`{
    "error": {
        "code": "BAD_REQUEST_ERROR",
        "description": "The requested URL was not found on the server.",
        "source": "NA",
        "step": "NA",
        "reason": "NA",
        "metadata": {}
    }
}`
![image](https://user-images.githubusercontent.com/57156681/139642389-5ce0154d-6931-4456-a802-0d4f39613ba4.png)

**Comment by Arfat-Mughal** [comment]
Once I remove /redirect at the end of URL 

![image](https://user-images.githubusercontent.com/57156681/139643284-be0fd2d4-bfd5-48b6-b1f1-b734940b71e7.png)

**Comment by ankitdas13** [comment]
Hi @Arfat-Mughal We have tested this API and it works, but you seem to be getting the error because you do not have this feature enabled. also you can this in [documentation](https://razorpay.com/docs/payments/payment-gateway/s2s-integration/json/v2/build-integration/cards/#12-create-a-payment) . 

<img width="866" alt="Screenshot 2022-09-01 at 9 13 57 AM" src="https://user-images.githubusercontent.com/89454448/187828327-f04fbf2c-63a7-4f45-a5b5-6dca9c2eafd3.png">
