### ISSUE TITLE
Customer already exists on edit call

### ISSUE THREAD

**Issue by rohitkhatri** [razorpay/razorpay-php#43]
Here's my code:

    $api = new \Razorpay\Api\Api(env('RAZORPAY_API_KEY'), env('RAZORPAY_API_SECRET'));
    $response = $api->customer->fetch('CUSTOMER_ID')->edit([
        'name'  => 'Rohit Khatri updated'
    ]);
    print_r($response);

It throws error:

BadRequestErrorCustomer already exists for the merchant - 400

**Comment by harman28** [comment]
@rohitkhatri Can you confirm that the payload is the same as the one shared here? The `customer already exists` error is thrown if you attempt update a customer such that the email-contact pair is no longer unique amongst your customers. 

It should, however, never be thrown if only name is being updated, since name is not required to be unique.

**Comment by harman28** [comment]
@rohitkhatri I'm fairly certain about the above diagnosis, i.e. the payload you had sent in the edit request resulted in the customer becoming identical to a different, existing customer. This is desirable behaviour.

I'm closing this issue for now, but if the diagnosis is wrong, or if you really were just sending `name` in the edit request (which should never result in this error), please feel free to reopen it.
