### ISSUE TITLE
Make the returned Object Public, $customer = $api->customer->create

### ISSUE THREAD

**Issue by kjhatis** [razorpay/razorpay-php#78]
Why this class is returning a protected array, which obviously will not be accessible outside of the class.
$customer = $api->customer->create
```

class Entity extends Resource implements ArrayableInterface {

    protected $attributes = array();


```
can't it be like ` ` protected $attributes = array();`` ?

**Comment by harman28** [comment]
Didn't quite understand the issue here.
You can access the attributes of the returned object as so:
```
$customer  = $api->customer->create($payload);
echo $customer->contact;
```
If you need access to the entire array of attributes, that's doable too:
```
$customerArray = $customer->toArray()
echo $customerArray['contact']
```

Closing this issue as I think this should solve your issue. If it does not do so, or if I have misunderstood your problem, please feel free to reply here or create a new issue.

**Comment by VivekShingala** [comment]
> Didn't quite understand the issue here. You can access the attributes of the returned object as so:
> 
> ```
> $customer  = $api->customer->create($payload);
> echo $customer->contact;
> ```
> 
> If you need access to the entire array of attributes, that's doable too:
> 
> ```
> $customerArray = $customer->toArray()
> echo $customerArray['contact']
> ```
> 
> Closing this issue as I think this should solve your issue. If it does not do so, or if I have misunderstood your problem, please feel free to reply here or create a new issue.

Thanks @harman28 it was helpful.
